[build]
  command = ""
  functions = "netlify/functions"

# ğŸ” RÃºt gá»n URL API
[[redirects]]
  from = "/doantuoi"
  to = "/.netlify/functions/doantuoi"
  status = 200

[[redirects]]
  from = "/time"
  to = "/.netlify/functions/time"
  status = 200
